import { useEffect, useMemo, useState } from 'react'
import { FiBell, FiBriefcase, FiCheck, FiChevronRight, FiCreditCard, FiFileText, FiGlobe, FiKey, FiLock, FiMail, FiMonitor, FiMoon, FiShield, FiSliders, FiSun, FiUser, FiUsers } from 'react-icons/fi'
import Avatar from '../components/ui/Avatar'
import { authApi } from '../api/authApi'
import { useAuthStore } from '../store/authStore'
import { useUIStore } from '../store/uiStore'
import './settingsReference.css'

const preferenceKey = 'sygmebec-settings-preferences'
const defaultPrefs = { notifications: true, mentions: true, weeklyDigest: true, reduceMotion: false, compact: false, publicProfile: true }
const groups = [
  ['Votre compte', [['profil', 'Profil public', FiUser], ['compte', 'Compte', FiBriefcase], ['apparence', 'Apparence', FiSliders], ['accessibilite', 'Accessibilité', FiMonitor], ['notifications', 'Notifications', FiBell]]],
  ['Accès', [['facturation', 'Facturation', FiCreditCard], ['emails', 'E-mails', FiMail], ['securite', 'Mot de passe et authentification', FiLock], ['sessions', 'Sessions', FiMonitor], ['api', 'Clés API', FiKey]]],
  ['Espace de travail', [['eglise', 'Église', FiGlobe], ['membres', 'Membres', FiUsers], ['moderation', 'Modération', FiShield]]],
  ['Archives', [['journal', 'Journal de sécurité', FiFileText]]],
]
const panels = {
  compte: ['Compte', 'Gérez les informations essentielles et la visibilité de votre compte.', 'Adresse e-mail de connexion', 'Cette adresse est utilisée pour sécuriser votre connexion.', 'Profil public', 'Autoriser les membres de l’église à voir votre profil.'],
  facturation: ['Facturation', 'Consultez votre abonnement et les informations de paiement de votre espace.', 'Offre actuelle', 'Votre abonnement est administré par SYGMEBEC.', 'Moyen de paiement', 'Aucun moyen de paiement personnel n’est requis.'],
  emails: ['E-mails', 'Personnalisez la réception de vos communications par e-mail.', 'Résumé hebdomadaire', 'Recevez un bilan de l’activité de votre église.', 'Communications système', 'Recevez les informations importantes liées au service.'],
  sessions: ['Sessions', 'Contrôlez les appareils connectés à votre compte.', 'Session actuelle', 'Navigateur actuel · activité à l’instant.', 'Autres sessions', 'Aucune autre session active détectée.'],
  api: ['Clés API', 'Créez des accès sécurisés pour vos intégrations techniques.', 'Aucune clé active', 'Les clés API permettent à des outils autorisés d’accéder à votre espace.', 'Accès développeur', 'Disponible uniquement pour les administrateurs.'],
  eglise: ['Église', 'Configurez les informations communes de votre espace de travail.', 'Informations de l’église', 'Nom, adresse, coordonnées et identité visuelle.', 'Préférences locales', 'Fuseau horaire, langue et paramètres de calendrier.'],
  membres: ['Membres', 'Définissez les règles de gestion et de confidentialité des membres.', 'Inscriptions en ligne', 'Acceptez les nouvelles demandes depuis le formulaire public.', 'Accès au registre', 'Les administrateurs et secrétaires autorisés peuvent gérer le registre.'],
  moderation: ['Modération', 'Gardez un espace sûr et bien organisé pour toute la communauté.', 'Validation des contenus', 'Les éléments signalés sont confiés à l’équipe de modération.', 'Conservation des données', 'Les éléments supprimés sont placés dans la corbeille avant suppression définitive.'],
  journal: ['Journal de sécurité', 'Suivez les opérations importantes effectuées dans votre espace.', 'Historique protégé', 'Les connexions et changements sensibles sont consignés automatiquement.', 'Export du journal', 'Disponible uniquement pour les administrateurs.'],
}
function Toggle({ checked, onChange, label }) { return <button type="button" className={`settings-toggle ${checked ? 'is-on' : ''}`} onClick={onChange} aria-pressed={checked} aria-label={label}><span /></button> }
function CardHeader({ Icon, title, description }) { return <header className="settings-card-head"><span className="settings-card-icon"><Icon /></span><div><h2>{title}</h2><p>{description}</p></div></header> }

export default function SettingsPage() {
  const { user, setUser } = useAuthStore()
  const { themePreference, setTheme } = useUIStore()
  const [active, setActive] = useState('profil')
  const [profile, setProfile] = useState({ prenom: '', nom: '', email: '', telephone: '' })
  const [prefs, setPrefs] = useState(() => { try { return { ...defaultPrefs, ...JSON.parse(localStorage.getItem(preferenceKey) || '{}') } } catch { return defaultPrefs } })
  const [notice, setNotice] = useState(null)
  const [saving, setSaving] = useState(false)
  const fullName = useMemo(() => `${profile.prenom} ${profile.nom}`.trim() || user?.identifiant || 'Administrateur', [profile, user])
  useEffect(() => setProfile({ prenom: user?.membre?.prenom || '', nom: user?.membre?.nom || '', email: user?.membre?.email || user?.email || '', telephone: user?.membre?.telephone || '' }), [user])
  useEffect(() => { localStorage.setItem(preferenceKey, JSON.stringify(prefs)); document.documentElement.classList.toggle('reduce-motion', prefs.reduceMotion) }, [prefs])
  const toggle = (key) => setPrefs((current) => ({ ...current, [key]: !current[key] }))
  const saveProfile = async () => { setSaving(true); try { const { data } = await authApi.updateMyProfile(profile); setUser({ ...user, membre: { ...user?.membre, ...data.membre } }); setNotice('Votre profil a été enregistré.') } catch { setNotice('Impossible d’enregistrer le profil pour le moment.') } finally { setSaving(false) } }
  const basicRow = (title, text, control) => <div className="settings-row"><div><b>{title}</b><span>{text}</span></div>{control}</div>
  const profilePanel = <article className="settings-card"><CardHeader Icon={FiUser} title="Profil public" description="Ces informations sont visibles par les membres de votre espace de travail." /><div className="settings-profile-row"><Avatar name={fullName} src={user?.membre?.photo} size="2xl" className="settings-avatar" /><div className="settings-profile-meta"><b>{fullName}</b><span>{profile.email || 'Aucune adresse e-mail'}</span></div><button type="button" className="settings-button">Modifier la photo</button></div>{basicRow('Nom', 'Votre nom apparaît dans le registre et les échanges.', <div className="settings-input-grid"><input value={profile.prenom} placeholder="Prénom" onChange={(e) => setProfile({ ...profile, prenom: e.target.value })} /><input value={profile.nom} placeholder="Nom" onChange={(e) => setProfile({ ...profile, nom: e.target.value })} /></div>)}{basicRow('Adresse courriel publique', 'Choisissez l’adresse affichée aux membres.', <input className="settings-profile-input" type="email" value={profile.email} onChange={(e) => setProfile({ ...profile, email: e.target.value })} />)}{basicRow('Téléphone', 'Utilisé uniquement pour les communications importantes.', <input className="settings-profile-input" value={profile.telephone} placeholder="+509 …" onChange={(e) => setProfile({ ...profile, telephone: e.target.value })} />)}<footer className="settings-card-footer"><p>Vos informations restent protégées.</p><button type="button" className="settings-button settings-primary" onClick={saveProfile} disabled={saving}>{saving ? 'Enregistrement…' : 'Enregistrer'}</button></footer></article>
  const appearancePanel = <article className="settings-card"><CardHeader Icon={FiSliders} title="Apparence" description="Adaptez l’interface à votre façon de travailler." />{basicRow('Thème', 'Choisissez l’apparence générale de l’application.', <div className="settings-segmented">{[['Clair', FiSun, 'light'], ['Sombre', FiMoon, 'dark'], ['Système', FiMonitor, 'system']].map(([label, Icon, value]) => <button key={value} type="button" className={themePreference === value ? 'active' : ''} onClick={() => setTheme(value)}><Icon />{label}</button>)}</div>)}{basicRow('Interface compacte', 'Réduit l’espacement pour afficher davantage d’informations.', <Toggle checked={prefs.compact} label="Interface compacte" onChange={() => toggle('compact')} />)}</article>
  const accessibilityPanel = <article className="settings-card"><CardHeader Icon={FiMonitor} title="Accessibilité" description="Réglez l’interface pour votre confort de lecture et de navigation." />{basicRow('Réduire les animations', 'Limite les transitions et les mouvements non essentiels.', <Toggle checked={prefs.reduceMotion} label="Réduire les animations" onChange={() => toggle('reduceMotion')} />)}{basicRow('Navigation au clavier', 'Les contrôles de l’application sont accessibles au clavier.', <span className="settings-button is-disabled">Activée</span>)}</article>
  const notificationsPanel = <article className="settings-card"><CardHeader Icon={FiBell} title="Notifications" description="Choisissez les alertes qui méritent votre attention." />{[['notifications', 'Notifications push', 'Alertes importantes en temps réel.'], ['mentions', 'Mentions et commentaires', 'Lorsqu’un membre vous cite ou vous répond.'], ['weeklyDigest', 'Résumé hebdomadaire', 'Un bilan de l’activité de votre église.']].map(([key, title, text]) => <div className="settings-row" key={key}><div><b>{title}</b><span>{text}</span></div><Toggle checked={prefs[key]} label={title} onChange={() => toggle(key)} /></div>)}</article>
  const securityPanel = <article className="settings-card"><CardHeader Icon={FiLock} title="Mot de passe et authentification" description="Protégez durablement l’accès à votre compte." />{basicRow('Mot de passe', 'Utilisez un mot de passe long, unique et difficile à deviner.', <button type="button" className="settings-button" onClick={() => setNotice('La modification du mot de passe est disponible depuis votre profil.')}>Modifier</button>)}{basicRow('Authentification à deux facteurs', 'Ajoute une vérification supplémentaire à votre connexion.', <button type="button" className="settings-button" disabled>Bientôt disponible</button>)}</article>
  const genericPanel = () => { const [title, description, a, aText, b, bText] = panels[active]; const Icon = groups.flatMap(([, items]) => items).find(([id]) => id === active)?.[2] || FiSliders; return <article className="settings-card"><CardHeader Icon={Icon} title={title} description={description} />{basicRow(a, aText, <button type="button" className="settings-button" disabled>Gérer bientôt</button>)}{basicRow(b, bText, <Toggle checked={active !== 'api' && active !== 'journal'} label={b} onChange={() => setNotice('Préférence mise à jour.')} />)}</article> }
  const content = active === 'profil' ? profilePanel : active === 'apparence' ? appearancePanel : active === 'accessibilite' ? accessibilityPanel : active === 'notifications' ? notificationsPanel : active === 'securite' ? securityPanel : genericPanel()
  return <div className="settings-page"><aside className="settings-sidebar"><div className="settings-brand"><span>EB</span><div><b>SYGMEBEC</b><small>Administration</small></div></div>{groups.map(([title, items]) => <div key={title}><p className="settings-nav-label">{title}</p><nav>{items.map(([id, label, Icon]) => <button key={id} type="button" className={active === id ? 'active' : ''} onClick={() => { setActive(id); setNotice(null) }}><Icon />{label}<FiChevronRight /></button>)}</nav></div>)}</aside><main className="settings-main"><header className="settings-hero"><div><span>Paramètres</span><h1>Votre espace, à votre image</h1><p>Gérez avec précision votre compte, vos accès et les réglages de votre église.</p></div><div className="settings-save-status"><i />Espace sécurisé</div></header>{notice && <div className="settings-message success"><span><FiCheck /></span>{notice}</div>}{content}<p className="settings-footnote">SYGMEBEC · Paramètres de votre espace d’administration</p></main></div>
}
