import { useEffect, useMemo, useRef, useState } from 'react'
import { useSearchParams } from 'react-router-dom'
import { FiBell, FiCamera, FiCheck, FiChevronRight, FiCloud, FiCreditCard, FiGrid, FiLock, FiMail, FiMonitor, FiMoon, FiRefreshCw, FiShield, FiSliders, FiSun, FiUser, FiX } from 'react-icons/fi'
import Avatar from '../components/ui/Avatar'
import { authApi } from '../api/authApi'
import { useAuthStore } from '../store/authStore'
import { useUIStore } from '../store/uiStore'
import './settingsReference.css'

const preferenceKey = 'sygmebec-settings-preferences'
const defaults = { digest: true, mentions: true, newMembers: false, push: true, product: false, twoFactor: false, reduceMotion: false, density: 'Standard', accent: '#c6a15b' }
const navItems = [['profil', 'Profil', FiUser], ['securite', 'Sécurité', FiShield], ['notifications', 'Notifications', FiBell], ['apparence', 'Apparence', FiSliders], ['facturation', 'Facturation', FiCreditCard], ['integrations', 'Intégrations', FiGrid]]
const notificationRows = [['digest', 'Résumé quotidien par e-mail', "Un récapitulatif de l'activité de votre église chaque matin."], ['mentions', 'Mentions et commentaires', "Une alerte immédiate lorsqu'un membre vous mentionne."], ['newMembers', 'Nouveaux membres', "Être informé lorsqu'une personne rejoint l'espace."], ['push', 'Notifications push', 'Alertes en temps réel sur vos appareils connectés.'], ['product', 'Actualités de la plateforme', "Nouveautés, améliorations et conseils d'utilisation."]]

function readPreferences() { try { return { ...defaults, ...JSON.parse(localStorage.getItem(preferenceKey) || '{}') } } catch { return defaults } }
function Toggle({ checked, onChange, label }) { return <button type="button" className={`settings-toggle ${checked ? 'is-on' : ''}`} onClick={onChange} aria-pressed={checked} aria-label={label}><span /></button> }
function SectionHeader({ icon: Icon, title, description }) { return <header className="settings-card-head"><span className="settings-card-icon"><Icon /></span><div><h2>{title}</h2><p>{description}</p></div></header> }

export default function SettingsPage() {
  const [searchParams, setSearchParams] = useSearchParams()
  const { user, setUser } = useAuthStore()
  const { theme, setTheme } = useUIStore()
  const [profile, setProfile] = useState({ prenom: '', nom: '', email: '', telephone: '' })
  const [preferences, setPreferences] = useState(readPreferences)
  const [passwordForm, setPasswordForm] = useState({ current_password: '', new_password: '', new_password_confirm: '' })
  const [showPassword, setShowPassword] = useState(false)
  const [isSaving, setIsSaving] = useState(false)
  const [isUploading, setIsUploading] = useState(false)
  const [isChangingPassword, setIsChangingPassword] = useState(false)
  const [message, setMessage] = useState(null)
  const fileInput = useRef(null)
  const sectionRefs = useRef({})
  const activeSection = searchParams.get('tab') === 'general' ? 'profil' : (searchParams.get('tab') || 'profil')
  const fullName = useMemo(() => `${profile.prenom} ${profile.nom}`.trim() || user?.identifiant || 'Administrateur', [profile, user])

  useEffect(() => { setProfile({ prenom: user?.membre?.prenom || '', nom: user?.membre?.nom || '', email: user?.membre?.email || user?.email || '', telephone: user?.membre?.telephone || user?.telephone || '' }) }, [user])
  useEffect(() => { localStorage.setItem(preferenceKey, JSON.stringify(preferences)); document.documentElement.style.setProperty('--settings-accent', preferences.accent); document.documentElement.classList.toggle('settings-compact', preferences.density === 'Compacte') }, [preferences])

  const updateUser = (membre) => setUser({ ...user, membre: { ...user?.membre, ...membre, nom_complet: `${membre?.prenom ?? profile.prenom} ${membre?.nom ?? profile.nom}`.trim() } })
  const chooseSection = (id) => { setSearchParams({ tab: id }); sectionRefs.current[id]?.scrollIntoView({ behavior: 'smooth', block: 'start' }) }
  const updatePreference = (key, value) => setPreferences((current) => ({ ...current, [key]: value ?? !current[key] }))

  const saveProfile = async () => {
    setIsSaving(true); setMessage(null)
    try { const { data } = await authApi.updateMyProfile(profile); updateUser(data.membre); setMessage({ type: 'success', text: 'Les informations du profil sont enregistrées.' }) }
    catch (error) { setMessage({ type: 'error', text: error.response?.data?.detail || 'La mise à jour du profil a échoué.' }) }
    finally { setIsSaving(false) }
  }
  const uploadPhoto = async (event) => {
    const file = event.target.files?.[0]
    if (!file) return
    if (!file.type.startsWith('image/')) return setMessage({ type: 'error', text: 'Veuillez choisir un fichier image.' })
    if (file.size > 20 * 1024 * 1024) return setMessage({ type: 'error', text: 'La photo ne doit pas dépasser 20 Mo.' })
    const formData = new FormData(); formData.append('photo', file); setIsUploading(true); setMessage(null)
    try { const { data } = await authApi.updateMyProfile(formData); updateUser(data.membre); setMessage({ type: 'success', text: 'La photo de profil a été mise à jour.' }) }
    catch { setMessage({ type: 'error', text: 'Impossible de mettre la photo à jour.' }) }
    finally { setIsUploading(false); event.target.value = '' }
  }
  const changePassword = async (event) => {
    event.preventDefault()
    if (!passwordForm.current_password || !passwordForm.new_password || !passwordForm.new_password_confirm) return setMessage({ type: 'error', text: 'Remplissez les trois champs pour modifier le mot de passe.' })
    if (passwordForm.new_password !== passwordForm.new_password_confirm) return setMessage({ type: 'error', text: 'Les nouveaux mots de passe ne correspondent pas.' })
    setIsChangingPassword(true); setMessage(null)
    try { const { data } = await authApi.changeMyPassword(passwordForm); setPasswordForm({ current_password: '', new_password: '', new_password_confirm: '' }); setShowPassword(false); setMessage({ type: 'success', text: data.message || 'Mot de passe modifié avec succès.' }) }
    catch (error) { const details = error.response?.data; const arrayError = details && typeof details === 'object' && Object.values(details).find((value) => Array.isArray(value)); setMessage({ type: 'error', text: arrayError?.[0] || details?.detail || 'Impossible de modifier le mot de passe.' }) }
    finally { setIsChangingPassword(false) }
  }
  const selectTheme = (nextTheme) => setTheme(nextTheme === 'Système' ? (window.matchMedia?.('(prefers-color-scheme: dark)').matches ? 'dark' : 'light') : nextTheme === 'Sombre' ? 'dark' : 'light')

  return <div className="settings-page">
    <aside className="settings-sidebar"><div className="settings-brand"><span>EB</span><div><b>SYGMEBEC</b><small>Administration</small></div></div><p className="settings-nav-label">Votre compte</p><nav>{navItems.slice(0, 3).map(([id, label, Icon]) => <button key={id} type="button" className={activeSection === id ? 'active' : ''} onClick={() => chooseSection(id)}><Icon />{label}<FiChevronRight /></button>)}</nav><p className="settings-nav-label">Espace de travail</p><nav>{navItems.slice(3).map(([id, label, Icon]) => <button key={id} type="button" className={activeSection === id ? 'active' : ''} onClick={() => chooseSection(id)}><Icon />{label}<FiChevronRight /></button>)}</nav><div className="settings-sidebar-user"><Avatar name={fullName} src={user?.membre?.photo} size="md" /><div><b>{fullName}</b><small>{user?.membre?.email || user?.identifiant || 'Compte administrateur'}</small></div></div></aside>
    <main className="settings-main"><header className="settings-hero"><div><span>Paramètres</span><h1>Votre espace, à votre image</h1><p>Gérez votre profil, la sécurité de votre compte, vos préférences de notification et les réglages de votre espace de travail.</p></div><div className="settings-save-status"><i />Toutes les modifications sont enregistrées</div></header>
      {message && <div className={`settings-message ${message.type}`}><span>{message.type === 'success' ? <FiCheck /> : <FiX />}</span>{message.text}<button type="button" onClick={() => setMessage(null)} aria-label="Fermer"><FiX /></button></div>}
      <section ref={(node) => { sectionRefs.current.profil = node }} id="profil" className="settings-section"><article className="settings-card"><SectionHeader icon={FiUser} title="Profil" description="Vos informations visibles par les membres de l’espace" /><div className="settings-profile-row"><Avatar name={fullName} src={user?.membre?.photo} size="2xl" className="settings-avatar" /><div className="settings-profile-meta"><b>{fullName}</b><span>{profile.email || user?.identifiant || 'Aucune adresse e-mail'}</span></div><button type="button" className="settings-button" onClick={() => fileInput.current?.click()} disabled={isUploading}><FiCamera />{isUploading ? 'Téléversement…' : 'Changer la photo'}</button><input ref={fileInput} className="settings-file-input" type="file" accept="image/png,image/jpeg,image/webp,image/gif" onChange={uploadPhoto} /></div><div className="settings-row settings-fields"><div><b>Informations personnelles</b><span>Affichées sur votre profil et dans les commentaires de l’équipe</span></div><div className="settings-input-grid"><input value={profile.prenom} onChange={(event) => setProfile((current) => ({ ...current, prenom: event.target.value }))} placeholder="Prénom" /><input value={profile.nom} onChange={(event) => setProfile((current) => ({ ...current, nom: event.target.value }))} placeholder="Nom" /></div></div><div className="settings-row settings-fields"><div><b>Adresse e-mail</b><span>Utilisée pour la connexion et les notifications importantes</span></div><input value={profile.email} type="email" onChange={(event) => setProfile((current) => ({ ...current, email: event.target.value }))} placeholder="adresse@exemple.com" /></div><div className="settings-row settings-fields"><div><b>Téléphone</b><span>Un moyen simple pour l’église de vous contacter</span></div><input value={profile.telephone} onChange={(event) => setProfile((current) => ({ ...current, telephone: event.target.value }))} placeholder="Ex. +509 00 00 0000" /></div><footer className="settings-card-footer"><p>PNG, JPG, WEBP ou GIF · 20 Mo maximum</p><button type="button" className="settings-button settings-primary" onClick={saveProfile} disabled={isSaving}>{isSaving ? 'Enregistrement…' : 'Enregistrer le profil'}</button></footer></article></section>
      <section ref={(node) => { sectionRefs.current.securite = node }} id="securite" className="settings-section"><article className="settings-card"><SectionHeader icon={FiShield} title="Sécurité" description="Protégez l’accès à votre compte" /><div className="settings-row"><div><b>Mot de passe</b><span>Utilisez un mot de passe unique et difficile à deviner</span></div><button type="button" className="settings-button" onClick={() => setShowPassword((value) => !value)}>{showPassword ? 'Fermer' : 'Modifier'}</button></div>{showPassword && <form className="settings-password-form" onSubmit={changePassword}><label>Mot de passe actuel<input type="password" value={passwordForm.current_password} autoComplete="current-password" onChange={(event) => setPasswordForm((current) => ({ ...current, current_password: event.target.value }))} /></label><label>Nouveau mot de passe<input type="password" value={passwordForm.new_password} autoComplete="new-password" onChange={(event) => setPasswordForm((current) => ({ ...current, new_password: event.target.value }))} /></label><label>Confirmer le nouveau mot de passe<input type="password" value={passwordForm.new_password_confirm} autoComplete="new-password" onChange={(event) => setPasswordForm((current) => ({ ...current, new_password_confirm: event.target.value }))} /></label><div><button className="settings-button settings-primary" disabled={isChangingPassword}>{isChangingPassword ? 'Modification…' : 'Mettre à jour le mot de passe'}</button></div></form>}<div className="settings-row"><div><b>Authentification à deux facteurs</b><span>Une couche de sécurité supplémentaire via une application dédiée</span></div><Toggle checked={preferences.twoFactor} label="Authentification à deux facteurs" onChange={() => updatePreference('twoFactor')} /></div><div className="settings-row"><div className="settings-session"><span><FiMonitor /></span><div><b>Cette session <em>Session actuelle</em></b><small>Navigateur actuel · dernière activité à l’instant</small></div></div><button type="button" className="settings-button is-disabled" disabled>Active</button></div><div className="settings-row"><div className="settings-session"><span><FiLock /></span><div><b>Autres sessions</b><small>La gestion des sessions distantes sera bientôt disponible.</small></div></div><button type="button" className="settings-button" disabled>Gérer bientôt</button></div></article></section>
      <section ref={(node) => { sectionRefs.current.notifications = node }} id="notifications" className="settings-section"><article className="settings-card"><SectionHeader icon={FiBell} title="Notifications" description="Choisissez ce qui mérite votre attention" />{notificationRows.map(([key, title, description]) => <div className="settings-row" key={key}><div><b>{title}</b><span>{description}</span></div><Toggle checked={preferences[key]} label={title} onChange={() => updatePreference(key)} /></div>)}</article></section>
      <section ref={(node) => { sectionRefs.current.apparence = node }} id="apparence" className="settings-section"><article className="settings-card"><SectionHeader icon={FiSliders} title="Apparence" description="Personnalisez l’interface de votre espace" /><div className="settings-row"><div><b>Thème</b><span>S’applique à l’ensemble de votre espace de travail</span></div><div className="settings-segmented">{[['Clair', FiSun], ['Sombre', FiMoon], ['Système', FiMonitor]].map(([label, Icon]) => <button key={label} type="button" className={(label === 'Sombre' && theme === 'dark') || (label === 'Clair' && theme === 'light') ? 'active' : ''} onClick={() => selectTheme(label)}><Icon />{label}</button>)}</div></div><div className="settings-row"><div><b>Couleur d’accent</b><span>Utilisée pour les boutons et éléments actifs de cette page</span></div><div className="settings-swatches">{['#c6a15b', '#4c7a5e', '#526ba7', '#a9536a'].map((color) => <button key={color} type="button" aria-label={`Accent ${color}`} className={preferences.accent === color ? 'active' : ''} style={{ background: color }} onClick={() => updatePreference('accent', color)} />)}</div></div><div className="settings-row"><div><b>Densité de l’interface</b><span>Ajuste l’espacement des listes et tableaux</span></div><div className="settings-segmented">{['Confortable', 'Standard', 'Compacte'].map((label) => <button key={label} type="button" className={preferences.density === label ? 'active' : ''} onClick={() => updatePreference('density', label)}>{label}</button>)}</div></div><div className="settings-row"><div><b>Réduire les animations</b><span>Limite les transitions et les effets de mouvement</span></div><Toggle checked={preferences.reduceMotion} label="Réduire les animations" onChange={() => updatePreference('reduceMotion')} /></div></article></section>
      <section ref={(node) => { sectionRefs.current.facturation = node }} id="facturation" className="settings-section"><article className="settings-card"><SectionHeader icon={FiCreditCard} title="Facturation" description="Abonnement et moyens de paiement" /><div className="settings-plan-grid">{[['Essentiel', 'Pour démarrer', ['Gestion des membres', 'Événements et annonces']], ['Pro', 'Recommandé', ['Rapports enrichis', 'Support prioritaire', 'Intégrations avancées']], ['Entreprise', 'Sur mesure', ['Accès multi-équipe', 'Accompagnement dédié']]].map(([name, price, features]) => <div key={name} className={`settings-plan ${name === 'Pro' ? 'selected' : ''}`}><h3>{name}</h3><strong>{price}</strong><ul>{features.map((feature) => <li key={feature}><FiCheck />{feature}</li>)}</ul></div>)}</div><div className="settings-row"><div><b>Offre de votre église</b><span>Les options d’abonnement sont gérées par l’administration de SYGMEBEC.</span></div><button type="button" className="settings-button" disabled>Géré par l’administration</button></div></article></section>
      <section ref={(node) => { sectionRefs.current.integrations = node }} id="integrations" className="settings-section"><article className="settings-card"><SectionHeader icon={FiGrid} title="Intégrations" description="Connectez les outils utilisés par votre équipe" />{[['Google Drive', 'Synchronisez les fichiers et documents partagés.', FiCloud], ['E-mail', 'Centralisez les notifications et communications.', FiMail], ['Automatisations', 'Créez des flux entre vos outils de travail.', FiRefreshCw]].map(([name, description, Icon]) => <div className="settings-row settings-integration" key={name}><div><span className="settings-integration-icon"><Icon /></span><div><b>{name}</b><span>{description}</span></div></div><button type="button" className="settings-button" disabled>Bientôt disponible</button></div>)}</article></section><p className="settings-footnote">Église Baptiste de l’Espoir · Espace d’administration</p>
    </main>
  </div>
}
