# Generated by Django 4.2.7 on 2026-07-21 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandeadhesion',
            name='actuellement_employe',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='demandeadhesion',
            name='actuellement_etudiant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='demandeadhesion',
            name='adresse',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='demandeadhesion',
            name='anciennete_ebec',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='demandeadhesion',
            name='classe_ecole_dimanche',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='demandeadhesion',
            name='dans_ecole_dimanche',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='demandeadhesion',
            name='date_affiliation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demandeadhesion',
            name='date_bapteme',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demandeadhesion',
            name='date_conversion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demandeadhesion',
            name='date_presentation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demandeadhesion',
            name='eglise_origine',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='demandeadhesion',
            name='etat_matrimonial',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='demandeadhesion',
            name='membre_petit_groupe',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='demandeadhesion',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='demandes-adhesion/photos/'),
        ),
        migrations.AddField(
            model_name='demandeadhesion',
            name='sexe',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='demandeadhesion',
            name='telephone_secondaire',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
