# Generated by Django 4.2.7 on 2026-08-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0003_demandeadhesion_niveau_etude'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandeadhesion',
            name='profession',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='demandeadhesion',
            name='zone_habitation',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='demandeadhesion',
            name='niveau_etude',
            field=models.CharField(
                blank=True,
                choices=[
                    ('PRIMAIRE', 'Primaire'),
                    ('SECONDAIRE', 'Secondaire'),
                    ('UNIVERSITAIRE', 'Universitaire'),
                    ('PROFESSIONNEL', 'Professionnel'),
                    ('AUTRE', 'Autre'),
                ],
                max_length=20,
            ),
        ),
    ]
