# Generated by Django 4.2.7 on 2026-06-27 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fonction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomFonction', models.CharField(max_length=100)),
                ('dateDebut', models.DateField()),
                ('dateFin', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Fonction',
                'verbose_name_plural': 'Fonctions',
                'db_table': 'fonction',
                'ordering': ['nomFonction'],
            },
        ),
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=150)),
                ('prenom', models.CharField(blank=True, max_length=150)),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('adresse', models.CharField(blank=True, max_length=255)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('date_adhesion', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Membre',
                'verbose_name_plural': 'Membres',
                'db_table': 'membre',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='Statut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Statut',
                'verbose_name_plural': 'Statuts',
                'db_table': 'statut',
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='MembreFonction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_assignation', models.DateField(auto_now_add=True)),
                ('fonction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membre_fonctions', to='members.fonction')),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membre_fonctions', to='members.membre')),
            ],
            options={
                'db_table': 'membre_fonction',
                'unique_together': {('membre', 'fonction')},
            },
        ),
        migrations.AddField(
            model_name='membre',
            name='fonctions',
            field=models.ManyToManyField(blank=True, related_name='membres', through='members.MembreFonction', to='members.fonction'),
        ),
        migrations.AddField(
            model_name='membre',
            name='statut',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='membres', to='members.statut'),
        ),
        migrations.CreateModel(
            name='HistoriqueStatut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancien_statut', models.CharField(max_length=50)),
                ('nouveau_statut', models.CharField(max_length=50)),
                ('date_changement', models.DateTimeField(auto_now_add=True)),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiques_statut', to='members.membre')),
                ('modifie_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statut_changements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historique de statut',
                'verbose_name_plural': 'Historiques de statut',
                'db_table': 'historique_statut',
                'ordering': ['-date_changement'],
            },
        ),
    ]
