# Generated by Django 4.2.7 on 2026-07-02 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membre',
            name='actuellement_employe',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membre',
            name='actuellement_etudiant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membre',
            name='anciennete_ebec',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='membre',
            name='date_signature',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membre',
            name='eglise_origine',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='membre',
            name='etat_matrimonial',
            field=models.CharField(blank=True, choices=[('CELIBATAIRE', 'Celibataire'), ('MARIE', 'Marie(e)'), ('SEPARE', 'Separe(e)'), ('DIVORCE', 'Divorce(e)'), ('VEUF', 'Veuf(ve)')], max_length=20),
        ),
        migrations.AddField(
            model_name='membre',
            name='membre_petit_groupe',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membre',
            name='sexe',
            field=models.CharField(blank=True, choices=[('MALE', 'Masculin'), ('FEMELLE', 'Femelle')], max_length=20),
        ),
        migrations.AddField(
            model_name='membre',
            name='signature_membre',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='membre',
            name='telephone_secondaire',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
