# Generated by Django 4.2.7 on 2026-07-03 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_seed_statuts'),
    ]

    operations = [
        migrations.AddField(
            model_name='membre',
            name='classe_ecole_dimanche',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='membre',
            name='dans_ecole_dimanche',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membre',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='membres/photos/'),
        ),
    ]
