# Generated by Django 4.2.7 on 2026-07-21 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_membre_classe_ecole_dimanche_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membre',
            name='date_affiliation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membre',
            name='date_bapteme',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membre',
            name='date_conversion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membre',
            name='date_presentation',
            field=models.DateField(blank=True, null=True),
        ),
    ]
