# Generated by Django 4.2.7 on 2026-08-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_membre_deleted_at_membre_deleted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='membre',
            name='niveau_etude',
            field=models.CharField(
                blank=True,
                choices=[
                    ('PRIMAIRE', 'Primaire'),
                    ('SECONDAIRE', 'Secondaire'),
                    ('UNIVERSITAIRE', 'Universitaire'),
                ],
                max_length=20,
            ),
        ),
    ]
