# Generated by Django 4.2.7 on 2026-09-14 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SportsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=96, unique=True)),
                ('description', models.CharField(blank=True, max_length=280)),
                ('color', models.CharField(blank=True, max_length=7)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Catégorie sportive',
                'verbose_name_plural': 'Catégories sportives',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SportsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('title', models.CharField(max_length=240)),
                ('slug', models.SlugField(max_length=270, unique=True)),
                ('excerpt', models.CharField(blank=True, max_length=700)),
                ('body', models.TextField()),
                ('sport', models.CharField(db_index=True, max_length=80)),
                ('country', models.CharField(blank=True, db_index=True, max_length=100)),
                ('haiti_focus', models.BooleanField(db_index=True, default=False)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('PUBLISHED', 'Publié')], db_index=True, default='DRAFT', max_length=12)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('cover_image_url', models.URLField(blank=True, max_length=900)),
                ('source_url', models.URLField(blank=True, max_length=900)),
                ('video_url', models.URLField(blank=True, max_length=900)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('reading_time', models.PositiveSmallIntegerField(default=1)),
                ('views', models.PositiveIntegerField(default=0)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sports_articles', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='sports.sportscategory')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Article sportif',
                'verbose_name_plural': 'Articles sportifs',
                'ordering': ['-published_at', '-created_at'],
                'indexes': [models.Index(fields=['status', 'published_at'], name='sports_spor_status_70c8be_idx'), models.Index(fields=['is_featured', 'status', 'published_at'], name='sports_spor_is_feat_f13c36_idx'), models.Index(fields=['haiti_focus', 'status', 'published_at'], name='sports_spor_haiti_f_e77195_idx')],
            },
        ),
    ]
