import { useEffect, useState } from 'react'
import { AnimatePresence, motion } from 'framer-motion'
import { ChevronLeft, ChevronRight, Image as ImageIcon, X } from 'lucide-react'

import SEO from '../components/common/SEO'
import AnimatedSection from '../components/ui/AnimatedSection'
import { publicApi, toMediaUrl } from '../services/publicApi'

export default function Galerie() {
  const [images, setImages] = useState([])
  const [loading, setLoading] = useState(true)
  const [selectedIndex, setSelectedIndex] = useState(null)
  useEffect(() => { publicApi.getGallery().then(({ data }) => setImages(data.results || data || [])).catch(() => setImages([])).finally(() => setLoading(false)) }, [])
  const selected = selectedIndex === null ? null : images[selectedIndex]
  const navigate = (direction) => setSelectedIndex((current) => (current + direction + images.length) % images.length)
  return <><SEO title="Galerie - SYGMEBEC" description="Les images ajoutées par l’église sur le tableau de bord." /><div className="py-20"><div className="container-custom"><div className="mx-auto mb-12 max-w-3xl text-center"><AnimatedSection><span className="section-subtitle"><ImageIcon className="h-4 w-4" /> Galerie</span></AnimatedSection><AnimatedSection delay={0.1}><h1 className="section-title mt-4">Nos <span className="gradient-text">souvenirs</span></h1></AnimatedSection><AnimatedSection delay={0.2}><p className="mt-4 text-lg text-gray-600">Découvrez les photos publiées par notre communauté.</p></AnimatedSection></div>{loading ? <p className="py-16 text-center text-gray-500">Chargement de la galerie…</p> : images.length === 0 ? <div className="py-16 text-center"><ImageIcon className="mx-auto mb-4 h-14 w-14 text-gray-300" /><p className="text-gray-500">Aucune image publiée pour le moment.</p></div> : <div className="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-3">{images.map((image, index) => <motion.button key={image.id} type="button" initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: index * 0.04 }} whileHover={{ y: -4 }} onClick={() => setSelectedIndex(index)} className="group overflow-hidden rounded-2xl bg-white text-left shadow-elegant"><img src={toMediaUrl(image.image)} alt={image.titre || 'Photo de la communauté'} className="h-72 w-full object-cover transition-transform duration-500 group-hover:scale-105" /><div className="p-4"><p className="font-semibold text-navy-900">{image.titre || 'Moment de communauté'}</p></div></motion.button>)}</div>}</div></div><AnimatePresence>{selected && <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} onClick={() => setSelectedIndex(null)} className="fixed inset-0 z-50 flex items-center justify-center bg-navy-900/95 p-4"><button type="button" className="absolute right-5 top-5 text-white" onClick={() => setSelectedIndex(null)}><X className="h-8 w-8" /></button><button type="button" className="absolute left-4 text-white" onClick={(event) => { event.stopPropagation(); navigate(-1) }}><ChevronLeft className="h-9 w-9" /></button><img src={toMediaUrl(selected.image)} alt={selected.titre || 'Photo de la communauté'} onClick={(event) => event.stopPropagation()} className="max-h-[85vh] max-w-[85vw] rounded-xl object-contain" /><button type="button" className="absolute right-4 text-white" onClick={(event) => { event.stopPropagation(); navigate(1) }}><ChevronRight className="h-9 w-9" /></button></motion.div>}</AnimatePresence></>
}
