# Generated by Django 4.2.7 on 2026-07-02 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='categorie',
            field=models.CharField(choices=[('CULTE', 'Culte'), ('PRIERE', 'Reunion de priere'), ('FORMATION', 'Formation'), ('JEUNESSE', 'Jeunesse'), ('CONFERENCE', 'Conference'), ('SOCIAL', 'Activite sociale'), ('AUTRE', 'Autre')], default='CULTE', max_length=30),
        ),
    ]
