# Generated by Django 4.2 on 2026-07-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_evenement_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='capacite',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evenement',
            name='est_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='evenement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='evenements/'),
        ),
    ]
