# Generated by Django 4.2.7 on 2026-07-21 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_evenement_vitrine_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeEvenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': "Type d'événement",
                'verbose_name_plural': "Types d'événements",
                'db_table': 'type_evenement',
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='evenement',
            name='type_evenement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evenements', to='events.typeevenement'),
        ),
    ]
