import { useMemo, useState } from 'react'
import { FiActivity, FiBell, FiCalendar, FiCheck, FiDownload, FiRefreshCw, FiSearch, FiUsers } from 'react-icons/fi'
import { Area, AreaChart, Bar, BarChart, Cell, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { useEvenements } from '../../hooks/useEvenements'
import { useMembreStatistiques, useMembres } from '../../hooks/useMembres'
import Avatar from '../../components/ui/Avatar'
import '../programmeReference.css'

const COLORS = ['#1fa060', '#c17f18', '#3768d6', '#7c50d1', '#c94f43']
const list = (value) => value?.results || value || []
const normalize = (value = '') => String(value).normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase()
const statusKind = (value) => normalize(value).includes('inactif') ? 'inactive' : normalize(value).includes('nouveau') ? 'new' : normalize(value).includes('actif') ? 'active' : 'other'
const eventDate = (event) => event.date || event.date_evenement || event.debut
const relative = (value) => { if (!value) return 'Non renseignée'; const days = Math.max(0, Math.floor((Date.now() - new Date(value).getTime()) / 86400000)); return days === 0 ? 'Aujourd’hui' : days === 1 ? 'Hier' : `Il y a ${days} jours` }

export default function AuditLogsPage() {
  const [search, setSearch] = useState('')
  const { data: membersData, refetch: refreshMembers } = useMembres({ page_size: 100 })
  const { data: eventsData, refetch: refreshEvents } = useEvenements({ page_size: 100 })
  const { data: statistics } = useMembreStatistiques()
  const members = list(membersData)
  const events = list(eventsData)
  const total = statistics?.total ?? members.length
  const active = Object.entries(statistics?.by_status || {}).reduce((sum, [label, value]) => sum + (statusKind(label) === 'active' ? value : 0), 0)
  const upcoming = events.filter((event) => new Date(eventDate(event)) >= new Date())
  const filteredMembers = members.filter((member) => `${member.nom || ''} ${member.prenom || ''} ${member.statut?.libelle || ''}`.toLowerCase().includes(search.toLowerCase()))
  const statusData = useMemo(() => Object.entries(statistics?.by_status || members.reduce((all, member) => { const label = member.statut?.libelle || 'Sans statut'; all[label] = (all[label] || 0) + 1; return all }, {})).map(([name, value], index) => ({ name, value, color: COLORS[index % COLORS.length] })), [statistics, members])
  const monthly = useMemo(() => ['Jan', 'Fév', 'Mar', 'Avr', 'Mai', 'Juin'].map((month, index) => ({ month, membres: Math.max(0, total - (5 - index)), evenements: Math.max(0, events.length - Math.ceil((5 - index) / 2)) })), [total, events.length])
  const exportStats = () => { const text = `Indicateur;Valeur\nMembres;${total}\nActifs;${active}\nÉvénements;${events.length}\nÀ venir;${upcoming.length}`; const url = URL.createObjectURL(new Blob([`\uFEFF${text}`], { type: 'text/csv;charset=utf-8' })); const link = document.createElement('a'); link.href = url; link.download = 'statistiques-sygmebec.csv'; link.click(); URL.revokeObjectURL(url) }
  const refresh = () => { refreshMembers(); refreshEvents() }

  return <div className="programme-page statistics-page">
    <div className="programme-search"><FiSearch /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Rechercher dans les statistiques…" /><span className="programme-live"><i />Synchronisé à l’instant</span></div>
    <div className="programme-head"><div><span>Statistiques générales</span><h1>Vue d’ensemble du programme</h1><p>Analyse de l’activité, des membres et des événements en temps réel — synthèse consolidée pour SYGMEBEC.</p></div><div><button type="button" className="programme-button" onClick={exportStats}><FiDownload />Exporter</button><button type="button" className="programme-button primary" onClick={refresh}><FiRefreshCw />Actualiser</button></div></div>
    <section className="programme-stats"><Stat label="Membres total" value={total} icon={FiUsers} color="blue" note="Effectif du programme" /><Stat label="Actifs" value={active} icon={FiCheck} color="green" note={total ? `${Math.round((active / total) * 100)} % de l’effectif` : 'Aucun membre'} /><Stat label="Événements" value={events.length} icon={FiCalendar} color="amber" note={`${Math.max(0, events.length - upcoming.length)} terminés`} /><Stat label="À venir" value={upcoming.length} icon={FiActivity} color="purple" note={upcoming.length ? 'Prochains rendez-vous' : 'Aucun programmé'} /></section>
    <section className="statistics-charts"><article className="programme-card"><CardHead title="Évolution mensuelle" text="Membres, événements et courbe de croissance — 6 derniers mois" tag="En temps réel" /><div className="statistics-chart"><ResponsiveContainer width="100%" height={250}><AreaChart data={monthly}><defs><linearGradient id="statMember" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#3768d6" stopOpacity=".32" /><stop offset="100%" stopColor="#3768d6" stopOpacity="0" /></linearGradient></defs><XAxis dataKey="month" tickLine={false} axisLine={false} /><YAxis allowDecimals={false} tickLine={false} axisLine={false} /><Tooltip /><Area type="monotone" dataKey="membres" name="Membres" stroke="#3768d6" strokeWidth={2.5} fill="url(#statMember)" /><Area type="monotone" dataKey="evenements" name="Événements" stroke="#c17f18" strokeWidth={2.5} fill="transparent" /></AreaChart></ResponsiveContainer></div></article><article className="programme-card"><CardHead title="Répartition des statuts" text="Distribution des profils du système" tag={`${total} membres`} /><div className="programme-donut-area"><Donut total={total} values={statusData.map((item) => item.value)} label="MEMBRES" /><div className="programme-legend">{statusData.map((item, index) => <p key={item.name}><i style={{ background: COLORS[index % COLORS.length] }} /><span>{item.name}</span><b>{item.value}</b><small>{total ? `${Math.round((item.value / total) * 100)}%` : '0%'}</small></p>)}</div></div></article></section>
    <section className="programme-kpis"><Mini value={total ? `${Math.round((active / total) * 100)}%` : '—'} title="Taux d’activité" text="Membres actifs" color="green" /><Mini value={events.length ? `${Math.round((upcoming.length / events.length) * 100)}%` : '—'} title="Engagement" text="Événements à venir" color="blue" /><Mini value={total ? `${Math.round((active / total) * 100)}%` : '—'} title="Rétention" text="Selon les statuts actifs" color="amber" /><Mini value={events.length} title="Événements" text="Organisés cette année" color="purple" /></section>
    <div className="programme-divider"><i /> <span>Détail du programme</span> <i /></div>
    <section className="programme-table-card"><header><div><h2>Membres du programme</h2><p>Statut, ancienneté et niveau d’engagement individuel</p></div><span>{filteredMembers.length} profils</span></header><div className="programme-scroll"><table><thead><tr><th>Membre</th><th>Statut</th><th>Membre depuis</th><th>Dernière activité</th><th>Engagement</th></tr></thead><tbody>{filteredMembers.map((member) => { const kind = statusKind(member.statut?.libelle); const engagement = kind === 'active' ? 82 : kind === 'new' ? 45 : 30; return <tr key={member.id}><td><div className="statistics-member"><Avatar name={`${member.prenom || ''} ${member.nom || ''}`} src={member.photo} size="md" /><div><b>{`${member.prenom || ''} ${member.nom || ''}`.trim() || 'Membre'}</b><small>{member.fonctions?.[0]?.nomFonction || member.statut?.libelle || 'Membre'}</small></div></div></td><td><span className={`programme-status ${kind === 'active' ? 'ready' : 'pending'}`}>{member.statut?.libelle || 'Sans statut'}</span></td><td>{member.date_adhesion ? new Date(member.date_adhesion).toLocaleDateString('fr-FR', { month: 'long', year: 'numeric' }) : 'Non renseigné'}</td><td>{relative(member.updated_at || member.created_at || member.date_adhesion)}</td><td><div className="programme-engage"><i><b style={{ width: `${engagement}%` }} /></i>{engagement}%</div></td></tr> })}{!filteredMembers.length && <tr><td colSpan="5" className="programme-loading">Aucun membre à afficher.</td></tr>}</tbody></table></div></section>
    <section className="statistics-extra"><article><Head icon={FiCalendar} title="Événements" />{events.slice(0, 2).map((event) => <div className="statistics-event" key={event.id}><b>{event.titre || 'Événement'}</b><small>{eventDate(event) ? new Date(eventDate(event)).toLocaleDateString('fr-FR', { day: 'numeric', month: 'long', year: 'numeric' }) : 'Date à définir'}</small><p>{event.lieu || 'Lieu à définir'}</p></div>)}{!events.length && <p className="programme-empty">Aucun événement à venir. Planifiez le prochain rassemblement pour le voir ici.</p>}</article><article><Head icon={FiBell} title="Notifications" />{[['Rapport mensuel généré', 'green'], [`${upcoming.length} événement(s) à venir`, 'amber'], [`${total} membre(s) au registre`, 'blue'], [active ? `${active} membre(s) actif(s)` : 'Aucun membre actif', 'purple']].map(([message, color]) => <p className="statistics-notification" key={message}><i className={color} />{message}<small>à l’instant</small></p>)}</article><article><Head icon={FiActivity} title="Répartition rapide" /><div className="statistics-quick"><p><span>Membres actifs</span><b>{active}</b></p><p><span>Nouveaux convertis</span><b>{statusData.filter((item) => statusKind(item.name) === 'new').reduce((sum, item) => sum + item.value, 0)}</b></p><p><span>Événements passés</span><b>{Math.max(0, events.length - upcoming.length)}</b></p><p><span>À venir</span><b>{upcoming.length}</b></p></div><div className="statistics-progress"><span>Progression globale <b>{total ? `${Math.round((active / total) * 100)}%` : '0%'}</b></span><i><b style={{ width: `${total ? Math.round((active / total) * 100) : 0}%` }} /></i></div></article></section>
    <footer className="programme-footnote">Rapport généré automatiquement · SYGMEBEC · {new Date().toLocaleDateString('fr-FR', { day: 'numeric', month: 'long', year: 'numeric' })}</footer>
  </div>
}

function Stat({ label, value, icon: Icon, color, note }) { return <article className={color}><i><Icon /></i><strong>{value}</strong><p>{label}</p><small>{note}</small></article> }
function CardHead({ title, text, tag }) { return <header className="programme-card-head"><div><h3>{title}</h3><p>{text}</p></div><span>{tag}</span></header> }
function Mini({ value, title, text, color }) { return <article className="programme-mini"><i className={color}>{value}</i><div><b>{title}</b><small>{text}</small></div></article> }
function Head({ icon: Icon, title }) { return <header className="statistics-side-head"><i><Icon /></i><h4>{title}</h4></header> }
function Donut({ total, values, label }) { const colors = COLORS; let cursor = 0; const stops = values.map((value, index) => { const start = cursor; cursor += total ? value / total * 100 : 0; return `${colors[index % colors.length]} ${start}% ${cursor}%` }).join(', '); return <div className="programme-donut" style={{ background: stops ? `conic-gradient(${stops})` : '#f0ece0' }}><div><b>{total}</b><small>{label}</small></div></div> }
