import { Link } from 'react-router-dom'
import { motion } from 'framer-motion'
import { BookOpen, Calendar, CheckCircle, Church, Users } from 'lucide-react'
import { Button } from '../ui/Button'
import { churchIntroduction } from '../../content/churchContent'

export default function Hero() {
  return <section className="relative isolate overflow-hidden bg-gradient-to-br from-primary-50 via-white to-gold-50/60 pb-16 pt-32 lg:pb-24"><div className="absolute inset-0 -z-10 bg-grid-pattern opacity-20" /><div className="container-custom"><div className="grid items-center gap-12 lg:grid-cols-2"><motion.div initial={{ opacity: 0, y: 24 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.6 }}><span className="inline-flex items-center gap-2 rounded-full border border-primary-200 bg-white/80 px-4 py-2 text-sm font-semibold text-primary-700 shadow-sm"><Church className="h-4 w-4 text-gold-600" /> Église Baptiste de l’Espoir</span><h1 className="mt-6 font-playfair text-4xl font-bold leading-tight text-navy-900 md:text-5xl xl:text-6xl">Bienvenue à l’Église Baptiste <span className="gradient-text">de l’Espoir</span> du Cap-Haïtien</h1><p className="mt-6 max-w-xl text-lg leading-relaxed text-gray-600">{churchIntroduction}</p><div className="mt-8 flex flex-wrap gap-4"><Link to="/adhesion"><Button variant="gold" size="lg"><Users className="h-5 w-5" /> Devenir membre</Button></Link><Link to="/a-propos"><Button variant="outline" size="lg"><BookOpen className="h-5 w-5" /> Notre foi</Button></Link></div><div className="mt-9 flex flex-wrap gap-7 border-t border-gray-200 pt-7 text-sm text-gray-600"><span className="inline-flex items-center gap-2"><CheckCircle className="h-5 w-5 text-primary-600" /> La Bible, notre autorité</span><span className="inline-flex items-center gap-2"><Calendar className="h-5 w-5 text-gold-600" /> Services chaque semaine</span></div></motion.div><motion.div initial={{ opacity: 0, scale: 0.96 }} animate={{ opacity: 1, scale: 1 }} transition={{ duration: 0.7, delay: 0.15 }} className="relative"><div className="overflow-hidden rounded-3xl bg-navy-900 shadow-premium"><img src="/eglise-ebec.png" alt="Église Baptiste de l’Espoir du Cap-Haïtien" className="h-[380px] w-full object-cover md:h-[520px]" /><div className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-navy-950/90 via-navy-900/20 to-transparent p-7 text-white"><p className="inline-flex items-center gap-2 rounded-full bg-white/15 px-4 py-2 text-sm backdrop-blur"><CheckCircle className="h-4 w-4 text-gold-300" /> Une église missionnaire</p></div></div></motion.div></div></div></section>
}
