# Generated by Django 6.0 on 2026-08-08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('members', '0005_membre_date_affiliation_membre_date_bapteme_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lettre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type_lettre', models.CharField(choices=[('RECOMMANDATION', 'Lettre de recommandation'), ('TRANSFERT', 'Lettre de transfert')], max_length=20)),
                ('destinataire', models.CharField(blank=True, max_length=200)),
                ('objet', models.CharField(max_length=220)),
                ('contenu', models.TextField(blank=True)),
                ('date_emission', models.DateField()),
                ('reference', models.CharField(blank=True, max_length=40, unique=True)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='lettres/')),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lettres_creees', to='accounts.utilisateur')),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lettres', to='members.membre')),
            ],
            options={'verbose_name': 'Lettre', 'verbose_name_plural': 'Lettres', 'db_table': 'lettre', 'ordering': ['-date_emission', '-id']},
        ),
    ]
