# Generated by Codex on 2026-08-21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('letters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lettre',
            name='type_lettre',
            field=models.CharField(
                choices=[
                    ('ATTESTATION', 'Lettre d’attestation'),
                    ('TRANSFERT', 'Lettre de transfert'),
                    ('RECOMMANDATION', 'Lettre de recommandation (ancienne)'),
                ],
                max_length=20,
            ),
        ),
    ]
