# Generated by Django 4.2.7 on 2026-06-27 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CritereFiltrage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(blank=True, max_length=50)),
                ('periode', models.CharField(blank=True, max_length=100)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('fonction', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Critère de filtrage',
                'verbose_name_plural': 'Critères de filtrage',
                'db_table': 'critere_filtrage',
            },
        ),
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('titre', models.CharField(max_length=200)),
                ('dateGeneration', models.DateTimeField(auto_now_add=True)),
                ('dateFin', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_COURS', 'En cours de génération'), ('TERMINE', 'Terminé'), ('ERREUR', 'Erreur')], default='EN_ATTENTE', max_length=20)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='rapports/')),
                ('error_message', models.TextField(blank=True)),
                ('critere', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rapport', to='reports.criterefiltrage')),
                ('genere_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapports', to='members.membre')),
            ],
            options={
                'verbose_name': 'Rapport',
                'verbose_name_plural': 'Rapports',
                'db_table': 'rapport',
                'ordering': ['-dateGeneration'],
            },
        ),
    ]
