# Generated by Django 4.2.7 on 2026-07-21 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='criterefiltrage',
            name='type_rapport',
            field=models.CharField(choices=[('MEMBRES', 'Membres'), ('FUNERAILLE', 'Funérailles'), ('MARIAGE', 'Mariages'), ('PRESENTATION_ENFANTS', 'Présentation des enfants'), ('PRESENTATION_TEMPLE', 'Présentation au temple'), ('AFFILIATION', 'Affiliations'), ('BAPTEMES', 'Quantité baptisée')], default='MEMBRES', max_length=30),
        ),
    ]
